default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: coding_challenge_development 

test:
  <<: *default
  database: coding_challenge_test

production:
  <<: *default
  database: coding_challenge_production
